name: qibla_plus
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  location: ^3.0.0
  flutter_compass: ^0.4.1
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: fonts/SF-Pro-Rounded-Bold.otf
        - asset: fonts/SF-Pro-Display-Light.otf
        - asset: fonts/SF-Pro-Display-Thin.otf
    - family: Dubai
      fonts:
        - asset: fonts/Dubai-Light.ttf
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-ExtraLight.ttf
        - asset: fonts/Tajawal-Light.ttf


